### PR TITLE
:bug: Add EJB, JPA rules and update some existing rules filecontent rules to use filePattern

### LINKED ISSUE #59: Java EE addon rules
These rules in the [java-ee](https://github.com/windup/windup/tree/master/rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules) are also important for tagging as well as facts. 

Here are some important ones I found:
- [x] DiscoverJPA(Configuration|Annotations)
- [x] DiscoverEJB(Configuration|Annotations)
- [x] DiscoverWebXML
- [x] DiscoverSpringConfigurationFile
- [ ] DiscoverHibernate (Tracked in #71)

Some of these rules store data into graph model which is later used in the reports. This is the information that we want to display into the "Facts" table. For example, the JPA rule goes and finds JPA configuration files,  searches for name of the JPA persistent units and stores them in graph. We want a generic way of storing this data (probably via Variables?) such that it can be displayed in UI.

### PR DESCRIPTION
**Pull request by pranavgaikwad**
Fixes #59

### CODE REVIEW

File: pkg/conversion/rules.go [hunk 1]
```diff
@@ -4,66 +4,32 @@ import "strings"
 
 // TODO: scope license file search to LICENSE files and use templates for tags to convert individual rules into one rule
 const license_rules = `
-- ruleID: apache-license-1
-  description: "Apache 1.0 license file"
+- ruleID: discover-license
+  description: "Discover project license"
+  tag:
+  - License={{matchingText}}
```
Comment (fabianvf) [inline pkg/conversion/rules.go:10]: This is cool
